steps:
  - name: 'gcr.io/cloud-builders/docker'
  args: [
    "build", 
    "-t", "gcr.io/$PROJECT_ID/ShadowSocks:latest",
    "."
  ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/backend:latest"]